import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export async function getStaticProps() {
    const allPostsData = {"name":"KAsia1"}
    return {
        props: {
            allPostsData,
        },
    };
}


export default function Home({allPostsData}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Quotes</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Quotes
                </h1>
                <h1 className={styles.title}>
                    <Link href="/quotes/index">
                        <a>{allPostsData.name}</a>
                    </Link>
                </h1>
            </main>
        </div>


)
}
